env: "local"

grpc_client:
  address: "localhost:50051"
  timeout: 5s

kafka_producer:
  broker: "kafkaDispatcherTest:9092"
  topic: "analytics"

http_server:
  address: "localhost:8082"
  timeout: 4s
  idle_timeout: 60s

postgres:
  host: "dbTest"
  port: "5432"
  username: "postgres"
  password: "password"
  db_name: "postgres"
  ssl_mode: "disable"

cycle_buffer:
  max_size: 10
